---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
        name: ğŸ”  Check for case conflicts
      - id: check-executables-have-shebangs
        name: ğŸ§ Check that executables have shebangs
        types: [text, executable]
        stages: [commit, push, manual]
      - id: check-json
        name: ï½› Check JSON files
        types: [json]
      - id: check-merge-conflict
        name: ğŸ’¥ Check for merge conflicts
        types: [text]
      - id: check-symlinks
        name: ğŸ”— Check for broken symlinks
        types: [symlink]
      - id: check-toml
        name: âœ… Check TOML files
        types: [toml]
      - id: check-xml
        name: âœ… Check XML files
        types: [xml]
      - id: check-yaml
        name: âœ… Check YAML files
        types: [yaml]
      - id: detect-private-key
        name: ğŸ•µï¸  Detect Private Keys
        types: [text]
      - id: end-of-file-fixer
        name: â®  Fix End of Files
        types: [text]
        stages: [commit, push, manual]
      - id: trailing-whitespace
        name: âœ„ Trim Trailing Whitespace
        types: [text]
        stages: [commit, push, manual]
      - id: check-ast
        name: ğŸ Check Python AST
        types: [python]
      - id: check-docstring-first
        name: â„¹ï¸  Check docstring is first
        types: [python]
      - id: no-commit-to-branch
        name: ğŸ›‘ Don't commit to main branch
        args: [--branch=main]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        name: ğŸ¶ Ruff Linter
        stages: [commit, push, manual]
        args: [--fix]
      - id: ruff-format
        name: ğŸ¶ Ruff Formatter
        stages: [commit, push, manual]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        name: ğŸ† Static type checking using mypy
        types: [python]
        additional_dependencies: []

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        name: ğŸ’„ Ensuring files are prettier
        types: [yaml, json, markdown]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: ğŸ—  Check YAML files with yamllint
        types: [yaml]

  - repo: local
    hooks:
      - id: uv
        name: ğŸ“œ Check pyproject with uv
        language: system
        entry: uv lock --check
        pass_filenames: false
        always_run: true
      - id: pylint
        name: ğŸŒŸ Starring code with pylint
        language: system
        types: [python]
        entry: uv run pylint
      - id: pytest
        name: ğŸ§ª Running tests and test coverage with pytest
        language: system
        types: [python]
        entry: uv run pytest --cov=tadoasync --cov-report=term-missing --cov-report=xml --cov-fail-under=95
        pass_filenames: false
