---
name: Linting

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFAULT_PYTHON: "3.12"

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up uv
        uses: astral-sh/setup-uv@v7
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        run: uv python install ${{ env.DEFAULT_PYTHON }}
      - name: ğŸ— Install Python dependencies
        run: uv sync
      - name: ğŸš€ Run ruff linter
        run: uv run ruff check --output-format=github .
      - name: ğŸš€ Run ruff formatter
        run: uv run ruff format --check .

  pre-commit-hooks:
    name: Pre-commit-hooks
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up uv
        uses: astral-sh/setup-uv@v7
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        run: uv python install ${{ env.DEFAULT_PYTHON }}
      - name: ğŸ— Install Python dependencies
        run: uv sync
      - name: ğŸš€ Check Python AST
        run: uv run prek run check-ast --all-files
      - name: ğŸš€ Check for case conflicts
        run: uv run prek run check-case-conflict --all-files
      - name: ğŸš€ Check docstring is first
        run: uv run prek run check-docstring-first --all-files
      - name: ğŸš€ Check that executables have shebangs
        run: uv run prek run check-executables-have-shebangs --all-files
      - name: ğŸš€ Check JSON files
        run: uv run prek run check-json --all-files
      - name: ğŸš€ Check for merge conflicts
        run: uv run prek run check-merge-conflict --all-files
      - name: ğŸš€ Check for broken symlinks
        run: uv run prek run check-symlinks --all-files
      - name: ğŸš€ Check TOML files
        run: uv run prek run check-toml --all-files
      - name: ğŸš€ Check XML files
        run: uv run prek run check-xml --all-files
      - name: ğŸš€ Check YAML files
        run: uv run prek run check-yaml --all-files
      - name: ğŸš€ Check YAML files
        run: uv run prek run check-yaml --all-files
      - name: ğŸš€ Detect Private Keys
        run: uv run prek run detect-private-key --all-files
      - name: ğŸš€ Check End of Files
        run: uv run prek run end-of-file-fixer --all-files
      - name: ğŸš€ Trim Trailing Whitespace
        run: uv run prek run trailing-whitespace --all-files

  pylint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up uv
        uses: astral-sh/setup-uv@v7
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        run: uv python install ${{ env.DEFAULT_PYTHON }}
      - name: ğŸ— Install Python dependencies
        run: uv sync
      - name: ğŸš€ Run pylint
        run: uv run prek run pylint --all-files

  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up uv
        uses: astral-sh/setup-uv@v7
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        run: uv python install ${{ env.DEFAULT_PYTHON }}
      - name: ğŸ— Install Python dependencies
        run: uv sync
      - name: ğŸš€ Run yamllint
        run: uv run yamllint .

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4.1.1
      - name: ğŸ— Set up uv
        uses: astral-sh/setup-uv@v7
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        run: uv python install ${{ env.DEFAULT_PYTHON }}
      - name: ğŸ— Install Python dependencies
        run: uv sync
      - name: ğŸ— Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: ğŸ— Install NPM dependencies
        run: npm install
      - name: ğŸš€ Run prettier
        run: uv run prek run prettier --all-files
